spring:
  application:
    name: authserver
  security:
    user:
      name: user
      password: password
  docker:
    compose:
      file: classpath:docker-compose.yaml
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 9000
  error:
    include-message: always

logging:
  level:
    org.springframework.security.oauth2.server.authorization: trace